import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cognive Academy",
  description: "Career-focused LMS for SQL, Python, Power BI, Git, MySQL, and Excel learning.",
  icons: {
    // Append a short cache-busting query so browsers fetch the latest files.
    icon: [
      { url: `/favicon.ico?v=${Date.now()}`, type: 'image/x-icon', sizes: '16x16 32x32 48x48' },
      { url: `/favicon-32.png?v=${Date.now()}`, type: 'image/png', sizes: '32x32' },
    ],
    shortcut: [{ url: `/favicon-32.png?v=${Date.now()}`, type: 'image/png', sizes: '32x32' }],
    apple: [{ url: `/apple-touch-icon-180.png?v=${Date.now()}`, sizes: '180x180' }],
  },
  themeColor: '#ffffff',
  manifest: '/site.webmanifest',
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <a href="#main" className="skip-link sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-50 focus:bg-white focus:px-3 focus:py-2 focus:rounded">Skip to content</a>
        {/* Preload critical font files generated by Next's font loader for FOIT mitigation */}
        <link rel="preload" href="/fonts/geist-sans.woff2" as="font" type="font/woff2" crossOrigin="anonymous" />
        <link rel="preload" href="/fonts/geist-mono.woff2" as="font" type="font/woff2" crossOrigin="anonymous" />
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
